#!/usr/bin/env python3
"""gen_bg_meta.py — 读背景图层 JSON → 产出 bg_{material}.{h,c}

用法:
  python3 tools/gen_bg_meta.py --material 森林

输入: output/{material}/json/410_502/variant_*_layers.json
输出: output/{material}/lvgl_export/meta/bg_{ascii_material}.{h,c}

契约:
  - bg_layer_meta_t 数组按 z_order 升序排列
  - bg_{material}_get(variant, &count) 查表 API
  - parallax_ratio 编码为 int16_t (x100 取整), 避免 float
"""

import argparse
import json
import math
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR) if os.path.basename(SCRIPT_DIR) == "tools" else SCRIPT_DIR

BG_PINYIN_MAP = {
    "森林": "forest",
}


def ascii_name(material):
    return BG_PINYIN_MAP.get(material, material)


def layer_var_name(ascii_mat, variant, layer_name):
    safe = layer_name.replace(" ", "_")
    safe = "".join(c if c.isalnum() or c == "_" else "_" for c in safe)
    return f"bg_{ascii_mat}_{variant}_{safe}"


def load_variants(json_dir):
    variants = {}
    for fname in sorted(os.listdir(json_dir)):
        if not fname.endswith("_layers.json"):
            continue
        variant = fname.replace("_layers.json", "").replace("variant_", "")
        with open(os.path.join(json_dir, fname), "r") as f:
            data = json.load(f)
        layers = sorted(data["layers"], key=lambda l: l["z_order"])
        variants[variant] = layers
    return variants


def gen_header(material, ascii_mat, variants):
    lines = []
    guard = f"BG_{ascii_mat.upper()}_H"
    lines.append("/* AUTO-GENERATED by 素材流水线/tools/gen_bg_meta.py. Do not edit. */")
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append('#include "lvgl/lvgl.h"')
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    const char            *name;            /* 图层名 (调试 + INI 索引) */")
    lines.append("    int16_t                z_order;")
    lines.append("    int16_t                parallax_ratio_x100;  /* 0..100, 实际值 = /100 */")
    lines.append("    int16_t                w, h;")
    lines.append("    const lv_image_dsc_t  *img;")
    lines.append("} bg_layer_meta_t;")
    lines.append("")

    # LV_IMAGE_DECLARE per layer per variant
    for variant in sorted(variants.keys()):
        for layer in variants[variant]:
            vname = layer_var_name(ascii_mat, variant, layer["name"])
            lines.append(f"LV_IMAGE_DECLARE({vname});")

    lines.append("")
    # extern arrays per variant
    for variant in sorted(variants.keys()):
        lines.append(f"extern const bg_layer_meta_t bg_{ascii_mat}_{variant}[];")
        lines.append(f"extern const uint8_t          bg_{ascii_mat}_{variant}_count;")

    lines.append("")
    lines.append(f"const bg_layer_meta_t *bg_{ascii_mat}_get(const char *variant, uint8_t *out_count);")
    lines.append("")
    lines.append("#endif")
    return "\n".join(lines) + "\n"


def gen_source(material, ascii_mat, variants):
    lines = []
    lines.append("/* AUTO-GENERATED by 素材流水线/tools/gen_bg_meta.py. Do not edit. */")
    lines.append(f'#include "bg_{ascii_mat}.h"')
    lines.append('#include <string.h>')
    lines.append("")

    for variant in sorted(variants.keys()):
        layers = variants[variant]
        lines.append(f"/* ── variant {variant}: {len(layers)} layers (z-ordered) ────────── */")
        lines.append(f"const bg_layer_meta_t bg_{ascii_mat}_{variant}[] = {{")
        for l in layers:
            px100 = round(l["parallax_ratio"] * 100)
            vname = layer_var_name(ascii_mat, variant, l["name"])
            lines.append(f'    {{ "{l["name"]}", {l["z_order"]}, {px100}, '
                         f'{TARGET_W}, {TARGET_H}, '
                         f'&{vname} }},')
        lines.append("};")
        lines.append(f"const uint8_t bg_{ascii_mat}_{variant}_count = {len(layers)};")
        lines.append("")

    # bg_{material}_get lookup
    lines.append(f"/* ── bg_{ascii_mat}_get ──────────────────────────── */")
    lines.append(f"const bg_layer_meta_t *bg_{ascii_mat}_get(const char *variant, uint8_t *out_count) {{")
    for variant in sorted(variants.keys()):
        lines.append(f'    if (strcmp(variant, "{variant}") == 0) {{')
        lines.append(f'        if (out_count) *out_count = bg_{ascii_mat}_{variant}_count;')
        lines.append(f'        return bg_{ascii_mat}_{variant};')
        lines.append(f'    }}')
    lines.append("    if (out_count) *out_count = 0;")
    lines.append("    return NULL;")
    lines.append("}")

    return "\n".join(lines) + "\n"


def main():
    p = argparse.ArgumentParser(description="gen_bg_meta — 背景图层元数据 C 代码生成")
    p.add_argument("--material", default="森林", help="素材名 (默认 森林)")
    p.add_argument("--target", default="410x502", help="输出分辨率 WxH (默认 410x502)")
    args = p.parse_args()

    material = args.material
    ascii_mat = ascii_name(material)
    tw, th = (int(x) for x in args.target.split("x"))

    global TARGET_W, TARGET_H
    TARGET_W, TARGET_H = tw, th

    json_dir = os.path.join(PROJECT_DIR, "output", material, "json", f"{tw}_{th}")
    out_dir = os.path.join(PROJECT_DIR, "output", material, "lvgl_export", "meta")

    variants = load_variants(json_dir)
    if not variants:
        print(f"ERROR: no variant JSON files found in {json_dir}", file=sys.stderr)
        return 1

    total_layers = sum(len(layers) for layers in variants.values())
    print(f"Found {len(variants)} variants, {total_layers} layers:")
    for v in sorted(variants.keys()):
        print(f"  variant_{v}: {len(variants[v])} layers")

    os.makedirs(out_dir, exist_ok=True)

    h_path = os.path.join(out_dir, f"bg_{ascii_mat}.h")
    c_path = os.path.join(out_dir, f"bg_{ascii_mat}.c")

    with open(h_path, "w") as f:
        f.write(gen_header(material, ascii_mat, variants))
    declares = sum(1 for _ in open(h_path) if "LV_IMAGE_DECLARE" in _)
    print(f"  → {h_path}  ({declares} LV_IMAGE_DECLAREs)")

    with open(c_path, "w") as f:
        f.write(gen_source(material, ascii_mat, variants))
    print(f"  → {c_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
