#!/usr/bin/env python3
"""gen_lvgl_meta.py — 读流水线 JSON → 产出 cat_parts_meta.{h,c}

用法:
  python3 tools/gen_lvgl_meta.py --material 小猫

输入: output/{material}/json/410_502/Cxx_default_positions.json × 15
输出: output/{material}/lvgl_export/meta/cat_parts_meta.{h,c}

契约 (LVGL 端依赖):
  - 数组顺序 = 渲染顺序 (z_order 升序, 底层→顶层)
  - LVGL 端按下标遍历即可, 无需读 z / 排序
  - 每个 skin 必备部件齐全, 同名部件不重复
  - 校验失败 → 非零退出, 不让有问题的数据流到 LVGL
"""

import argparse
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR) if os.path.basename(SCRIPT_DIR) == "tools" else SCRIPT_DIR

ANIM_MAP = {
    "wag":    "PART_ANIM_WAG",
    "bounce": "PART_ANIM_BOUNCE",
    "spin":   "PART_ANIM_SPIN",
    "blink":  "PART_ANIM_BLINK",
    None:     "PART_ANIM_NONE",
}

# 部件→anim 白名单 (优先于 JSON click_anim, 对齐 config.CLICK_ANIM_MAP)
PART_CLICK_ANIM = {
    "Eye1":  "blink",
    "Eye2":  "blink",
    "Tails": "wag",
    "Hat":   "bounce",   # H+: click_part hat 需要 bounce
}

# 每个 skin 必须包含的部件 (所有 15 角色都有的核心 8 件)
REQUIRED_PARTS = ["Shadow", "Body", "Eye1", "Tails", "Hand_B", "Hand_F", "Leg_B", "Leg_F"]


def part_var_name(char_id, part_name):
    safe = part_name.replace(" ", "_")
    return f"cat_{char_id}_{safe}"


def img_ref(char_id, file_path):
    """从 "C01/Hand_F.png" → "&cat_C01_Hand_F" """
    basename = os.path.basename(file_path)
    name = os.path.splitext(basename)[0]
    safe = name.replace(" ", "_")
    return f"&cat_{char_id}_{safe}"


def load_characters(json_dir):
    """读 15 份 JSON, 每角色 parts 按 z_order 升序排好"""
    chars = {}
    for fname in sorted(os.listdir(json_dir)):
        if not fname.endswith("_default_positions.json"):
            continue
        char_id = fname.split("_")[0]
        with open(os.path.join(json_dir, fname), "r") as f:
            data = json.load(f)
        parts = data["parts"]
        parts.sort(key=lambda p: p["z_order"])
        chars[char_id] = parts
    return chars


def validate(chars):
    """校验必备部件 + 同名唯一。失败打印错误并返回非零"""
    errors = []

    for cid in sorted(chars.keys()):
        parts = chars[cid]
        names = [p["name"] for p in parts]

        # 1. 同名部件唯一
        seen = set()
        for n in names:
            if n in seen:
                errors.append(f"[{cid}] duplicate part: {n}")
            seen.add(n)

        # 2. 必备部件齐全
        missing = [r for r in REQUIRED_PARTS if r not in names]
        if missing:
            errors.append(f"[{cid}] missing required parts: {missing}")

    if errors:
        print("VALIDATION FAILED:")
        for e in errors:
            print(f"  ❌ {e}")
        return False

    print("Validation passed: all 15 skins have required 8 parts, no duplicates.")
    return True


def collect_part_declares(chars):
    part_set = set()
    for _cid, parts in chars.items():
        for p in parts:
            part_set.add(part_var_name(_cid, p["name"]))
    return sorted(part_set)


def gen_header(chars, part_declares):
    lines = []
    lines.append("/* AUTO-GENERATED by 素材流水线/tools/gen_lvgl_meta.py. Do not edit. */")
    lines.append("/*")
    lines.append(" * 数组顺序 = 渲染顺序 (z_order 升序, 底层 → 顶层)。")
    lines.append(" * LVGL 端按下标顺序遍历即可, 无需读 z / 排序。")
    lines.append(" * Phase B v2: cat_full 系列已下线, LVGL 端用 cat_parts_get 逐部件组装。")
    lines.append(" */")
    lines.append("#ifndef CAT_PARTS_META_H")
    lines.append("#define CAT_PARTS_META_H")
    lines.append("")
    lines.append('#include "lvgl/lvgl.h"')
    lines.append('#include "../driver/animal_driver.h"')
    lines.append("")
    lines.append("/* ── part_meta_t ───────────────────────────── */")
    lines.append("/* 数组已按 z_order 升序排列, LVGL 遍历即得正确渲染顺序 */")
    lines.append("typedef struct {")
    lines.append("    const char *name;")
    lines.append("    int16_t  x, y, w, h;")
    lines.append("    int16_t  pivot_x, pivot_y;")
    lines.append("    int16_t  rotation_01;         /* 0.1 deg */")
    lines.append("    const lv_image_dsc_t *img;")
    lines.append("    part_anim_type_t anim_type;")
    lines.append("} part_meta_t;")
    lines.append("")
    lines.append("/* ── 全部部件 ──────────────────────────────── */")
    for v in part_declares:
        lines.append(f"LV_IMAGE_DECLARE({v});")
    lines.append("")
    lines.append("/* ── 每角色部件数组 (已按 z 升序排好) ──────── */")
    for cid in sorted(chars.keys()):
        lines.append(f"extern const part_meta_t cat_parts_{cid}[];")
        lines.append(f"extern const uint8_t      cat_parts_{cid}_count;")
    lines.append("")
    lines.append("/* ── 查表 API ──────────────────────────────── */")
    lines.append("const part_meta_t *cat_parts_find(const char *char_id, const char *part_name);")
    lines.append("const part_meta_t *cat_parts_get(const char *char_id, uint8_t *out_count);")
    lines.append("")
    lines.append("#endif")
    return "\n".join(lines) + "\n"


def gen_source(chars):
    lines = []
    lines.append('/* AUTO-GENERATED by 素材流水线/tools/gen_lvgl_meta.py. Do not edit. */')
    lines.append('/*')
    lines.append(' * 数组顺序 = 渲染顺序 (z_order 升序, 底层 → 顶层)。')
    lines.append(' * LVGL 端按下标顺序遍历即可, 无需读 z / 排序。')
    lines.append(' */')
    lines.append('#include "cat_parts_meta.h"')
    lines.append('#include <string.h>')
    lines.append('')

    for cid in sorted(chars.keys()):
        parts = chars[cid]
        lines.append(f"/* ── {cid}: {len(parts)} parts (z-ordered) ────────── */")
        lines.append(f"const part_meta_t cat_parts_{cid}[] = {{")
        for p in parts:
            click_anim = PART_CLICK_ANIM.get(p["name"], p.get("click_anim"))
            anim = ANIM_MAP.get(click_anim, "PART_ANIM_NONE")
            rot_01 = round(p["rotation"] * 10)
            img = img_ref(cid, p["file"])
            lines.append(f'    {{ "{p["name"]}", {p["x"]}, {p["y"]}, {p["w"]}, {p["h"]}, '
                         f'{p["pivot_x"]}, {p["pivot_y"]}, {rot_01}, '
                         f'{img}, {anim} }},')
        lines.append("};")
        lines.append(f"const uint8_t cat_parts_{cid}_count = {len(parts)};")
        lines.append("")

    # cat_parts_find — 按名查单个部件
    lines.append("/* ── cat_parts_find ─────────────────────────── */")
    lines.append("const part_meta_t *cat_parts_find(const char *char_id, const char *part_name) {")
    for cid in sorted(chars.keys()):
        parts = chars[cid]
        lines.append(f'    if (strcmp(char_id, "{cid}") == 0) {{')
        for i, p in enumerate(parts):
            lines.append(f'        if (strcmp(part_name, "{p["name"]}") == 0)')
            lines.append(f'            return &cat_parts_{cid}[{i}];')
        lines.append(f'    }}')
    lines.append("    return NULL;")
    lines.append("}")
    lines.append("")

    # cat_parts_get — 返回整个数组 + 计数, LVGL 遍历即得正确渲染顺序
    lines.append("/* ── cat_parts_get ──────────────────────────── */")
    lines.append("/* 返回已按 z 升序排好的部件数组 + 计数, LVGL 按下标遍历即可 */")
    lines.append("const part_meta_t *cat_parts_get(const char *char_id, uint8_t *out_count) {")
    for cid in sorted(chars.keys()):
        lines.append(f'    if (strcmp(char_id, "{cid}") == 0) {{')
        lines.append(f'        if (out_count) *out_count = cat_parts_{cid}_count;')
        lines.append(f'        return cat_parts_{cid};')
        lines.append(f'    }}')
    lines.append("    if (out_count) *out_count = 0;")
    lines.append("    return NULL;")
    lines.append("}")

    return "\n".join(lines) + "\n"


def main():
    p = argparse.ArgumentParser(description="gen_lvgl_meta — 角色部件元数据 C 代码生成")
    p.add_argument("--material", default="小猫", help="素材名 (默认 小猫)")
    args = p.parse_args()

    material = args.material
    json_dir = os.path.join(PROJECT_DIR, "output", material, "json", "410_502")
    out_dir = os.path.join(PROJECT_DIR, "output", material, "lvgl_export", "meta")

    chars = load_characters(json_dir)
    if not chars:
        print(f"ERROR: no JSON files found in {json_dir}", file=sys.stderr)
        return 1

    print(f"Found {len(chars)} characters: {', '.join(sorted(chars.keys()))}")
    for cid in sorted(chars.keys()):
        print(f"  {cid}: {len(chars[cid])} parts")

    if not validate(chars):
        return 1

    part_declares = collect_part_declares(chars)

    os.makedirs(out_dir, exist_ok=True)

    h_path = os.path.join(out_dir, "cat_parts_meta.h")
    c_path = os.path.join(out_dir, "cat_parts_meta.c")

    with open(h_path, "w") as f:
        f.write(gen_header(chars, part_declares))
    print(f"  → {h_path}  ({len(part_declares)} part declares)")

    with open(c_path, "w") as f:
        f.write(gen_source(chars))
    print(f"  → {c_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
